---
title: "Exploratory Data Analysis"
author: "CJ Piccio and Collin Pucher"
date: '2022-08-04'
output: html_document
---

*This exploratory analysis of America's favorite past-time takes an in-depth look at how the Negro Leagues altered the style of play in Baseball through statistics alone.*

#### Our Data

The data we are using is pulled from baseballreference. This site gets its data from seamheads which utilizes newspapers, articles, and other first-hand accounts of baseball statistics to gather stats. The data we will be using in our project takes a look at 1929 and 1937 negro and MLB league teams. Our primary objective is to highlight how much more aggressive the negro league teams were in their play style compared to MLB teams. To do this, we will be pulling certain statistics (such as (stolen bases and sacrifice hits) to average out and plot in an attempt to visualize our conclusions.

The data we are using is from Baseball Reference, though it was compiled by Seamheads from newspapers and other primary sources of the time. It is important to note that the data set is not complete by any means, as box scores and record keeping were not as comprehensive in the Negro Leagues as they were for the American and National Leagues. In addition, the Negro Leagues played many exhibition, barnstorming, and other types of games that are not included in the data set. 

Our data includes all Negro League pitchers and position players from 1920 to 1948 (the period they have been designated major leagues by MLB) in the Baseball Reference database, with the aforementioned caveats.

#### Broad overview

Here is an interactive visual of on-base percentage (OBP) on the X-axis and slugging percentage (SLG) on the Y-axis for Negro Leaguers from 1920 to 1948 with at least 100 plate appearances.

```{r include = FALSE}
library(tidyverse)
library(plotly)
library(RColorBrewer)

all_1920_48_qb <- read.csv("data/NegroLeagueBatters1920to1948.csv")
all_1920_48_qb <- arrange(all_1920_48_qb, PA)

all_ops_plot_2048 <- ggplot(data = all_1920_48_qb, aes(OBP, SLG, col = PA, label = Player)) + 
                   geom_point(aes(size = PA)) + labs(x = "On-base percentage", y = "Slugging percentage", 
                                       title = "1920 to 1948 Negro League batters, > 100 PA") 
all_ops_plotly_2048 <- ggplotly(all_ops_plot_2048)
all_ops_plotly_2048
```

#### A Summary
